inherit_from: .rubocop_todo.yml
require: rubocop-rails

Metrics/LineLength:
  Max: 120

Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb

Style/SymbolArray:
  EnforcedStyle: percent

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
