inherit_from: .rubocop_todo.yml
require: rubocop-rails

Layout/LineLength:
  Max: 120
  Exclude:
    - config/initializers/devise.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*.rb
    - app/controllers/graphql_controller.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/RedundantPercentQ:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/SymbolArray:
  EnforcedStyle: percent

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Rails/FilePath:
  EnforcedStyle: arguments

Rails/EnumHash:
  Enabled: false
